### ISSUE TITLE
Incorrectly published version 2.0.1 as 2.0.2 to NPM

### ISSUE THREAD

**Issue by constgen** [barraponto/neutrino-preset-vue#2]
If you currently will set the dependency in the **package.json**
```"neutrino-preset-vue": "^2.0.2"```
and check versions with
```> npm outdated```
you will see that versions doesn't match even after fresh install
```
PS C:\Projects\neutrino-project-playground> npm outdated
Package              Current  Wanted  Latest  Location
neutrino-preset-vue    2.0.1   2.0.2   2.0.2  neutrino-project-playground
```
This is because wrong version in the module **package.json**

**Comment by barraponto** [comment]
Yeah, I made some stupid things with publishing. I published since, so maybe this is no longer an issue.
Please reopen if it's not fixed yet.

**Comment by constgen** [comment]
Closed
